name: Build

on:
  push:
    branches: [main]
  pull_request:

env:
  DUMBKY_VERSION: 0.1.0

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            goos: linux
            icon: assets/icon.png
          - os: windows-latest
            goos: windows
            icon: assets/icon.ico
          - os: macos-latest
            goos: darwin
            icon: assets/icon.png

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.3"

      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y gcc libgl1-mesa-dev xorg-dev libxkbcommon-dev

      - name: Install Windows Dependencies
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          choco install mingw -y
          echo "C:\tools\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install macOS Dependencies
        if: matrix.os == 'macos-latest'
        run: xcode-select --install || true

      - name: Install fyne CLI
        run: go install fyne.io/tools/cmd/fyne@latest
        env:
          GOBIN: ${{ github.workspace }}/bin

      - name: Package Fyne App (Debug)
        if: github.ref != 'refs/heads/main'
        run: ${{ github.workspace }}/bin/fyne package --os ${{ matrix.goos }} --icon ${{ matrix.icon }} --name Dumbky --app-id com.christianwsmith.dumbky --app-version $DUMBKY_VERSION

      - name: Package Fyne App (Release)
        if: github.ref == 'refs/heads/main'
        run: ${{ github.workspace }}/bin/fyne package --os ${{ matrix.goos }} --icon ${{ matrix.icon }} --name Dumbky --app-id com.christianwsmith.dumbky --app-version $DUMBKY_VERSION --release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dumbky-${{ matrix.goos }}
          path: |
            *.exe
            *.dmg
            *.app
            *.tar.xz
            *.tar.gz
            *.zip
            *.desktop
